// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[]           = "d63e35b6-0824-4bfc-bae3-b0ca0b3974f6";
const char DEVICE_LOGIN_NAME[]  = "57bd44cd-6fe8-4da9-9ef2-6b79bc76d5da";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onSpotifyanzeigeChange();

CloudDimmedLight spotifyanzeige;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(spotifyanzeige, READWRITE, ON_CHANGE, onSpotifyanzeigeChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
